name: Drc CI/CD
on:
  push:
    branches:
      - "drc"

  pull_request:
    branches:
     - "drc"

env:
  CI: false
  env_drc: ${{secrets.ENV_DRC}}

jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: drc

      - name: create environment file
        run: |
          touch ./.env && echo "$env_drc" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push web
        id: build-push-web
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: esatya/vendor-app-pwa:drc
          
      - name: Build an Image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .